config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  get '/', to: 'home#index', as: :home

  # For Menu
  get "/menu", to: "menus#index", :as => :menu
  post "/menu", to: "menus#create"
  delete "/menu/:id", to: "menus#delete"



  # For MenuList
  # get all data as json
  get "/menus", to: "menu_lists#index", :as => :menu_list
  post "/menus", to: "menu_lists#create"
  delete "/menus/:id", to: "menu_lists#delete"
  delete "/cancel/:id", to: "menu_lists#cancelOrder"
  get "menus/order/:id", to: "menu_lists#orderStatus", :as => :order_status

  # Sign Up
  get "/users", to: "users#new", :as => :signup
  post "/users", to: "users#create" 

  # SignIn (Session Page)
  get "/signin", to: "sessions#new", :as => :signin
  post "/signin", to: "sessions#create"
  
  # SignOut
  get "/signout", to: "sessions#destroy", :as => :signout

  # Cart List
  get "/cart", to: "cart_items#new", :as => :cart
  post "/cart", to: "cart_items#create" 
  delete "/cart/:id", to: "cart_items#destroy"

  # Checkout
  get "/order", to: "order_items#new", :as => :order
  post "/order", to: "order_items#create"

  #Admin
  get "/admin", to: "admin#new", :as => :admin
  get "/order/details/:id", to:"admin#getOrderById", :as => :orders
  get "/admin/details/:id", to: "admin#getById", :as => :details
  get "/admin/newList", to: "admin#newList", :as => :newList
  get "admin/order/:id", to: "admin#orderDetails", :as => :orderDetails
  post "/newMenu", to: "admin#createNewMenu", :as => :new_menu
  post "/setid", to: "admin#setId", :as => :set_id
  post "/admin/newList", to: "admin#createNewList"
  patch "/admin/updateOrder/:id", to: "admin#updateOrder"
  delete "/admin/details/:id", to:"admin#deleteMenuList"
  delete "/delete/:id", to:"admin#deleteMenuTitle" 
  
  #Cashier
  get "cashier", to: "cashier#new", :as => :cashier
  patch "/cashier/updateOrder/:id", to: "cashier#updateOrder"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :menu_list
end

app/models/menu.rb
class Menu < ApplicationRecord
 has_many :menu_lists
end

app/models/menu_list.rb
class MenuList < ApplicationRecord
    belongs_to :menu
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :menu_list
end

app/models/session.rb
class Session < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
    has_many :orders # for cashier


    has_secure_password
    validates :password, presence: true
    validates :user_name, presence: true
    validates :user_name, length: {minimum: 3}
    validates :password, length: {minimum: 4}

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :ensure_user_role, except: [:setId, :getId]
   
    $main_id = nil
    
    def new
        @getAllOrders = Order.all
        @getAllMenuTitles = Menu.all
        render 'index'
    end

    def getOrderById
        id = params[:id]
        @orderDetails = Order.find(id).order_items
    end

    def getById
        id = params[:id]
        $getId = id
        @title = Menu.find(id).menu_title
        @details = Menu.find(id).menu_lists
        render 'detail'
    end

    def orderDetails
        @order_id = params[:id]
        render 'order_details'
    end

    def updateOrder
        id = params[:id]
        Order.update(id,delivered_at: true)
        redirect_to admin_path
    end

    def deleteMenuList
        id = params[:id]
        MenuList.delete(id)
        redirect_to admin_path
    end

    def newList 
       render 'add_list'
    end

    def createNewMenu
        new_menuTitle = Menu.new(
            menu_title: params[:menu_title]
        )
        if new_menuTitle.save
            redirect_to admin_path
        else
            flash[:error] = new_menuTitle.errors.full_messages.join(", ")
            redirect_to admin_path
        end        
    end

    def createNewList
        menu = MenuList.new(
            menu_id: params[:menu_id],
            menu_name: params[:menu_name],
            menu_description: params[:menu_description],
            menu_price: params[:menu_price]
        )
        if menu.save
            redirect_to admin_path
        else    
            flash[:error]  = menu.id #menu.errors.full_messages.join(", ")
            redirect_to newList_path
        end
    end

    def deleteMenuTitle
        id = params[:id]
        menus = MenuList.where(:menu_id => id)
        menus.each do |menu|
            menu.destroy
        end     
        Menu.delete(id)
        redirect_to admin_path
    end

    def setId
        if  $main_id == nil
            $main_id = Menu.first.id
        else
            $main_id = Menu.find(params[:id]).id   
        end
        redirect_to admin_path
    end

    def getId
        if $main_id == nil
            $main_id = Menu.first.id
        else
            return $main_id
        end        
    end 

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
end

app/controllers/cashier_controller.rb
class CashierController < ApplicationController
    before_action :ensure_cashier_role

    def new
        render 'index'
    end

    def updateOrder
        id = params[:id]
        Order.update(id,delivered_at: true)
        redirect_to cashier_path
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def index
        if current_user
            if current_user.role == "admin"
                redirect_to admin_path
            elsif current_user.role == "cashier"
                redirect_to cashier_path
            else   
                redirect_to menu_list_path
            end
        else     
           render 'index'
        end
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in
 
  def new 
    render 'new'
  end 

  def create
    new_user = User.new(
      user_name: params[:user_name],
      password: params[:password],
      role: "user"
    )

    if new_user.save
        redirect_to home_path
    else
       flash[:error]  = new_user.errors.full_messages.join(", ")
       redirect_to signup_path
    end
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_lists_helper.rb
module MenuListsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/add_list.html.erb
<section class="Admin-Add">
    <h2>Add New Menu List</h2>
    <section class = "User-section">
        <%= form_with url: "/admin/newList" do |form|%>
            <div class = "User-Flex">
                <p class = "FormInput-label">Menu Name : </p>
                <%= form.text_field :menu_name, class: "UserForm-input"%>
            </div>
            <div class = "User-Flex">
                <p class = "FormInput-label">Menu Description: </p>
                <%= form.text_field :menu_description, class: "UserForm-input" %>
            </div>
            <div class = "User-Flex">
                <p class = "FormInput-label">Menu Price: </p>
                <%= form.number_field :menu_price, class: "UserForm-input" %>
            </div>
            <%= form.hidden_field :menu_id, value: $getId %>
            <div class = "Form-section">
                <%= form.submit "Save", :class => "btn btn-dark btn-lg" %>
            </div>
        <%end%>
    </section>
</section>

app/views/admin/detail.html.erb
<section class="Admin-Details">
  <h2><%= @title %></h2>
  <%= form_with url: "/admin/newList", method: :get do |form|%>
    <%= form.submit "+ Add Items" ,class:"btn btn-primary"%>
  <% end %>     
</section>
<hr>

<section class="Admin-Details-Section">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Menu Name</th>
        <th scope="col">Menu Description</th>
        <th scope="col">Price</th>
        <th scope="col">Cancel</th>
      </tr>
    </thead>
    <tbody>
    <% @details.each do |item|%>
      <tr>
        <td><%= item.menu_name%></td>
        <td><%= item.menu_description %></td>
        <td><%= item.menu_price%></td>
        <td><%= form_with url: "/admin/details/#{item.id}", method: :delete do |form|%>
            <%= form.submit "Delete" ,class:"Admin-Details-Delete"%>
            <% end %>
        </td>
      </tr>
    <% end %>  
    </tbody>  
  </table>  
</section>

app/views/admin/index.html.erb
<section class="Admin">
  <h2 class="Menu-Title">Menu Title: </h2>
  <div class="Admin-AddForm">
    <%=form_with(url: new_menu_path, method: 'post') do |form|%>
      <%= form.text_field :menu_title, {:placeholder => 'Add Title',:required => true} %>
      <%= form.submit 'Add', class: "Admin-Add-btn"%>
    <% end %>
  </div>  
</section>
 
<section class = "Admin-Sections">
  <div class="container">
    <div class="row">
      <% @getAllMenuTitles.each do |title|%>
        <div class="col">
        <div class="card" style="padding:2em;">
        <h3><%= title.id %>. <%= title.menu_title %></h3> Menu items: <%=Menu.find(title.id).menu_lists.count%>
          <%= form_with url: "/admin/details/#{title.id}", method: :get do |form|%>
            <%= form.submit "Details" ,class:"btn btn-info"%>
          <% end %>
          <%= form_with url: "/delete/#{title.id}", method: :delete do |form|%>
            <%= form.submit "Delete" ,class:"btn btn-danger"%>
          <% end %>
        </div>
        </div>
      <% end %>  
    </div>
  </div>    
  <div class="Admin-Set-Menu">
    <%=form_with(url: set_id_path, method: 'post') do |form|%>
      <%= form.number_field :id, {:placeholder => 'Enter Main Menu Id',:required => true} %>
      <%= form.submit 'Set', class: "Admin-Add-btn"%>
    <% end %>
  </div> 
</section>


<section class="Admin-View">
  <h2 class="Order-Section">Orders:</h2>

  <div class="container">
    <div class="row">
    <% User.all.each do |user|%>
      <% if user.orders.count>0%>
      <div class="col">
      <div class="card" style="padding:2em;">
      <h3><%= user.id %>. <%= user.user_name %></h3>
      <h4>View Order<h4>       
            <%= form_with url: "/admin/order/#{user.id}", method: :get do |form|%>
              <%= form.submit "Details" ,class:"btn btn-dark"%>
            <% end %>  
      </div>        
      </div>
      <% end %>
      <% end %>
    </div>
  </div>  

  

app/views/admin/order_details.html.erb
<section class="Admin-Order-Details">
  <h1>Order details of <%= User.find(@order_id).user_name %></h1>
  <% total_sum=0 %> 
  <% User.find(@order_id).orders.each do |order| %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Menu Name</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
          <h2>Order Id: <%=order.id%></h2>
          <h4>Order Date: <%= order.order_date%></h4>
          <% sum=0 %>
          <% order.order_items.each do |item| %>
          <tr>
              <td><%= item.menu_list_id %></td>
              <td><%= item.menu_item_name %></td>
              <td><%= item.menu_item_price%>₹
              <% sum+=item.menu_item_price %></td>  
          </tr>
          <% end %>
      </tbody>
    </table>   
    <div>
      <h3>Total: </h3>
      <h3><%=sum%></h3>
    </div>
    <div>
    <%if order.delivered_at == nil || false%>
      <%= form_with url: "/admin/updateOrder/#{order.id}", method: :patch do |form|%>
        <%= form.submit "Deliver" ,class:"btn btn-success"%>
      <% end %>
    <%else%> 
      <%= form_with url: "/admin/updateOrder/#{order.id}", method: :patch do |form|%>
        <%= form.submit "Delivered" ,class:"btn btn-secondary", disabled: true%>
      <% end %> 
    <% end %>
    <div>
    <% total_sum+=sum%>
  <% end %> 
  <hr>
  <div class="TotalSum">
    <h2>Net Price: </h2> 
    <h2><%=total_sum%></h2>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <% if @current_user %>
      <section class="Session">
        <h1> Welcome <%= @current_user.user_name %> </h1>
        <div class="links">
          <% if @current_user.role == "user" %> <!--cart only for user-->
            <%= link_to "Cart", cart_path, method: "get", class: "Session-link-1" %>
          <% end %> 
            <%= link_to "Sign-out", signout_path, method: "get", class: "Session-link"%>
        </div>
      </section>
        
   
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>  
    <% end %>  

    <%= yield %>
  </body>
</html>