config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  get '/', to: 'home#index', as: :home

  # For Menu
  get "/menu", to: "menus#index", :as => :menu
  post "/menu", to: "menus#create"
  delete "/menu/:id", to: "menus#delete"



  # For MenuList
  # get all data as json
  get "/menus", to: "menu_lists#index", :as => :menu_list
  post "/menus", to: "menu_lists#create"
  delete "/menus/:id", to: "menu_lists#delete"
  delete "/cancel/:id", to: "menu_lists#cancelOrder"
  get "menus/order/:id", to: "menu_lists#orderStatus", :as => :order_status

  # Sign Up
  get "/users", to: "users#new", :as => :signup
  post "/users", to: "users#create" 

  # SignIn (Session Page)
  get "/signin", to: "sessions#new", :as => :signin
  post "/signin", to: "sessions#create"
  
  # SignOut
  get "/signout", to: "sessions#destroy", :as => :signout

  # Cart List
  get "/cart", to: "cart_items#new", :as => :cart
  post "/cart", to: "cart_items#create" 
  delete "/cart/:id", to: "cart_items#destroy"

  # Checkout
  get "/order", to: "order_items#new", :as => :order
  post "/order", to: "order_items#create"

  #Admin
  get "/admin", to: "admin#new", :as => :admin
  get "/order/details/:id", to:"admin#getOrderById", :as => :orders
  get "/admin/details/:id", to: "admin#getById", :as => :details
  get "/admin/newList", to: "admin#newList", :as => :newList
  get "admin/order/:id", to: "admin#orderDetails", :as => :orderDetails
  post "/newMenu", to: "admin#createNewMenu", :as => :new_menu
  post "/setid", to: "admin#setId", :as => :set_id
  post "/admin/newList", to: "admin#createNewList"
  patch "/admin/updateOrder/:id", to: "admin#updateOrder"
  delete "/admin/details/:id", to:"admin#deleteMenuList"
  delete "/delete/:id", to:"admin#deleteMenuTitle" 
  
  #Cashier
  get "cashier", to: "cashier#new", :as => :cashier
  patch "/cashier/updateOrder/:id", to: "cashier#updateOrder"

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :menu_list
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    
    def new
        if Cart.exists?
            cart = Cart.last
            @cart_items = cart.cart_items
            render 'index'
        else 
            render 'empty'
        end   
    end

    def get_cart_id
        if Cart.exists? 
            return Cart.last.id
        else
            Cart.create(
                cart_date: Date.today,
                user_id: current_user.id # try to change this to a better form 
            )
            return Cart.last.id
        end
    end


    def create
        CartItem.create(
            cart_id: get_cart_id,
            menu_list_id: params[:menu_list_id],
            menu_list_name: params[:menu_list_name],
            menu_list_price: params[:menu_list_price]
        )
        redirect_to menu_list_path
    end

    def destroy
        id = params[:id]
        CartItem.delete(id)
        redirect_to cart_path
    end

end

app/views/cart_items/empty.html.erb
<h1>Cart Empty</h1>

app/views/cart_items/index.html.erb
<section class="Cart">
   <h1>Cart</h1>
   <h4><a class="Cart-Link" href="/menus">Back To Menu</a><h4>
</section>
<hr>
<section class="Cart-Session">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Menu Name</th>
      <th scope="col">Menu Price</th>
      <th scope="col">Cancel</th>
    </tr>
  </thead>
  <% sum = 0 %>
  <% @cart_items.each do |item| %>
  <tbody>
    <tr>
      <td><%= item.menu_list_id %></td>
      <td><%= item.menu_list_name %></td>
      <td><%= item.menu_list_price%>₹ <% sum+=item.menu_list_price %> </td>
      <td class= "Cart-Button"> <%= form_with url: "/cart/#{item.id}", method: :delete do |form|%>
      <%= form.submit "Delete" ,class:"btn btn-danger"%>
      <% end %> </td>
    </tr>
  </tbody>
  <% end %>  
  </table>
  <div class=Item-Headers>
    <h3>Total Price<h3>
    <h3><%= sum %>₹</h3>
  </div> 
</section>
<hr>
<%= form_with url: order_path do |form|%>
  <%= form.hidden_field :total, value: sum %>
  <%= form.submit "Order",class:"btn btn-success" %>
<%end%>